### ISSUE TITLE
Social Icons are stacked oddly in footer of /business

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#3097] opened 2019-02-22 23:02 UTC
![screen shot 2019-02-22 at 3 52 20 pm](https://user-images.githubusercontent.com/385234/53276176-42dbdc00-36bb-11e9-8342-d2bfbba7afce.png)

**Comment by kevincrafts** [comment] 2019-02-25 16:16
Closing this as a duplicate of #3100

**Closed as completed by kevincrafts** 2019-02-25 16:16 UTC
