### ISSUE TITLE
Re-add field_collection 7.x-1.0-beta12 now that 

### ISSUE THREAD

**Issue by owenmorrill** [CuBoulder/express#859] opened 2017-03-03 15:29 UTC
## Context

Now that https://github.com/CuBoulder/atlas/pull/187 has been merged in, we need to try updating field collection to its beta12 release. If, when this is pushed up to dev or test, the db update still seg faults, we'll need to return to beta11 of the module.

## Process

Update field_collection to 7.x-1.0-beta12. 

## Expected result

Updates with no seg faults.

## Current result

Currently one beta version behind.

## Possible Fix

Upgrade to beta12.

## Screenshots

----

**Comment by kreynen** [comment] 2017-05-15 17:27
While this update hook should have been batched, this specific seg fault issue identified in https://www.drupal.org/node/2855820 was most likely caused by the db timeouts specific to test.

**Comment by alexfinnarn** [comment] 2017-05-16 20:57
Marking as closed since this code is merged into dev and should end up in 2.4.0 release.

**Closed by alexfinnarn** 2017-05-16 20:57 UTC
Labels: type:Bug
