### ISSUE TITLE
Honeypot "Leave this field blank" Showing up on Exposed Views when all filter options are hidden

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#1571] opened 2017-09-20 23:09 UTC
This was reported in [EXP-9688]. Repurposing this issue to deal with moving to a blacklisting of specific core forms (and all webforms) approach vs. trying to apply to all forms.

## Context

On the embed_templates module, I was using a form field called "URL" and the form field wasn't saving. It took me awhile, but then I remembered Honeypot used a field called URL too. 

## Process

1. Login to site as a [SO, CE, EO, ADMIN or DEV]
2. Save a node form with a field called 'url'.
3. Edit the node to see the URL field isn't saved.

## Possible Fix

Add permissions for logged in user roles to bypass Honeypot. Also explicitly define forms needed instead of putting it on all forms.

**Comment by kreynen** [comment] 2018-05-21 15:32
![edit_article_list_page_research___innovation_office_enews___research__amp__innovation_office_and_research___innovation_office_enews___research___innovation_office___university_of_colorado_boulder](https://user-images.githubusercontent.com/385234/40315855-ca8e42bc-5cd9-11e8-81b9-50bbdace16ce.png)

**Comment by cathysnider** [comment] 2018-05-21 16:19
So far I've been unable to find a duplicate of this problem: 
https://www.colorado.edu/english/alumni-news-and-publications
https://www.colorado.edu/changelab/news

**Closed** 2018-06-05 15:16 UTC
Labels: type:Bug
