### ISSUE TITLE
Video filter config not correct on newly provisioned sites.

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express#990] opened 2017-03-29 14:17 UTC
## Context

Reported in Jira EXP-6165. Video shortcode isn't working

## Process

1. Login to site as a DEV
2. Visit `/admin/config/content/formats/wysiwyg`
3. Click Video Filter
4. Check selected codecs. 

* Try to save hand edited list of codecs, fails to save.

## Expected result

Per http://www.colorado.edu/webcentral/tutorial/v2/embed-video
```
Archive.org, Blip.tv, Capped, College Humor, DailyMotion, Flickr Slideshows, Flickr Video, Game Trailers, Game Videos, Google Video, Meta Cafe, MySpace, Picasa Slideshows, Slideshare, Streamhoster, Teachertube, TED, Vimeo, Wistia, YouTube, YouTube (Playlist).
```
## Current result

Only one selected is `whatchado`

* Cache clear allows you to save new list

## Screenshots

![video_filter](https://cloud.githubusercontent.com/assets/4621248/24459132/0980e464-1458-11e7-82f0-87a6543f230b.png)

**Comment by kreynen** [comment] 2017-06-26 16:37
Duplicate of https://github.com/CuBoulder/express/issues/918

**Closed by kreynen** 2017-06-26 16:37 UTC
Labels: type:Bug
