### ISSUE TITLE
"Delete URL Redirects" is throwing an error

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2039] opened 2018-03-20 20:29 UTC
## Context

Login as Dev or SO on any Web Express site
Go to Settings >> URL Redirects >> Delete redirects  and click 'Continue" 
(direct link: admin/config/search/redirect/delete)
You will receive an error 

## Screenshots

![screen shot 2018-03-20 at 2 25 50 pm](https://user-images.githubusercontent.com/638275/37680813-a51cd68e-2c4a-11e8-895d-e037d90f820b.png)
----

## Links to Examples

with login link:
https://www.colorado.edu/user
https://www.colorado.edu/webcentral/user
https://www.colorado.edu/visit/user
https://www.colorado.edu/alumni/user
https://www.colorado.edu/cmci/user
https://www.colorado.edu/business/user

**Comment by jwfuller** [comment] 2018-03-20 20:41
Duplicate of https://github.com/CuBoulder/express/issues/1812

**Closed by jwfuller** 2018-03-20 20:41 UTC
Labels: type:Bug
