### ISSUE TITLE
2.4.0 - Update Error - Test - Business, Alumni, amath, jewishstudies, homepage

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express#1077] opened 2017-05-25 21:00 UTC
```
[osr_web_deploy@wwebtest4 ~]$ cd /data/web/express/p13dc88589aa
[osr_web_deploy@wwebtest4 p13dc88589aa]$ drush updb -y
 Cu_core           7023  Enable cu_profile_module_manager module
 Cu_seo_bundle     7002  Enable metatag_opengraph module.
 Cu_users          7025  Update user_external_invite email template for when invite is first sent.
 Field_collection  7008  Update fields in field collections already set to use Entity Translation.
Do you wish to run all pending updates? (y/n): y

WD bean: EntityMalformedException: Missing bundle property on entity of type bean. in entity_extract_ids() (line 7929 of                                                [error]
/data/code/cores/drupal/drupal-7.54/includes/common.inc).
Missing bundle property on entity of type bean.                                                                                                                         [error]
Performed update: field_collection_update_7008                                                                                                                          [ok]
Performed update: cu_users_update_7025                                                                                                                                  [ok]
Performed update: cu_seo_bundle_update_7002                                                                                                                             [ok]
Performed update: cu_core_update_7023                                                                                                                                   [ok]
'all' cache was cleared.                                                                                                                                                [success]
Finished performing updates.                                                                                                                                            [ok]
```

**Comment by kreynen** [comment] 2017-05-26 14:58
I'm guessing this is being caused by the $item->save(TRUE); in http://cgit.drupalcode.org/field_collection/tree/field_collection.install?h=7.x-1.x#n383 and that if we identify the entity that can't be resaved we should be able to save the node with that field_collection through the UI either.

**Comment by alexfinnarn** [comment] 2017-05-30 20:57
marking as a duplicate of the referenced bug with more detail.

**Closed by alexfinnarn** 2017-05-30 20:57 UTC
Labels: type:Bug, type:Duplicate
